---

- name: Install essential packages
  apt: name={{item}} state=latest
  with_items:
  - vim
  - wget
  - curl
  - git
  - python
  - tree
  - colordiff
  - build-essential
  - cmake


- name: Configure default locale
  apt: name=locales state=latest
- locale_gen: name=en_US.UTF-8 state=present
- shell: /usr/sbin/update-locale LANG=en_US.UTF-8 LC_ALL=en_US.UTF-8
  changed_when: False
- copy: content='export LC_ALL=en_US.UTF-8\nexport LANG=en_US.UTF-8\nexport LANGUAGE=en_US:en\n' dest=/etc/profile.d/utf8_locale.sh owner=root group=root mode=0644


- name: Install OpenJDK 8
  apt: name=openjdk-8-jdk state=latest
- copy: content='export JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64\nexport PATH=$PATH:$JAVA_HOME/bin\n' dest=/etc/profile.d/openjdk.sh owner=root group=root mode=0644


- include: docker.yml

- include: youcompleteme.yml
